### PR TITLE
Ignore value nullability

### PR DESCRIPTION
**Pull request by brabeji**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix

* **What is the current behavior?** (You can also link to an open issue here)

The link validates the response data but does not account for `@skip` and `@include` directives.

* **What is the new behavior (if this is a feature change)?**

The link now disregards result value type nullability. We should just convert scalars and don't bother with the nullability validation (apollo client does this). This fixes the link raising errors for non-nullable fields even when they're skipped with `@skip` directive. This should also take care of `@include` directive, but this is yet to be tested.

### CODE REVIEW

**Comment by eturino** [comment]
@brabeji LGTM but lint fails in CI. Could you fix that? I probably will change that lint rule later tbh…

**Comment by brabeji** [comment]
@eturino Definitely, I was just probing if this is a valid change. Will fix asap

**Comment by eturino** [comment]
I am thinking about this change a bit more. Indeed this link should not be responsible to ensure null/non-nulls. While your change fixes it for that case, it wouldn't do it on a nested field.

Maybe what we can do is to change the behaviour of `ensureNullableType` (https://github.com/eturino/apollo-link-scalars/blob/0014120b876d52251bdcb12a935a28d8e8fad27e/src/lib/ensure-nullable-type.ts)

We call this at the beginning of `treatValue()`. What if instead of calling that, we call directly `getNullableType()`?

We would have to adapt this test https://github.com/eturino/apollo-link-scalars/blob/1f8fbf57876a25787baabe6d63b133db336bbb5c/src/__tests__/validate-enums-from-query.spec.ts#L188

What do you think @brabeji ?

**Comment by eturino** [comment]
I've added an issue #29 to cover the removal of the nullability checks.

**Comment by brabeji** [comment]
> What if instead of calling that, we call directly `getNullableType()`?

Yes, that makes sense. I wasn't digging deep enough!

I have some issues with the resulting TS type, which I was unable to solve yet, though. See https://github.com/eturino/apollo-link-scalars/pull/28/files#diff-a5b54a3eee29198834db8832951d216eR69

**Comment by brabeji** [comment]
I've compared coverage results with master and I can't see any increase in uncovered lines. Does it look like -0.2% might be expected change when removing code?

**Comment by eturino** [comment]
@brabeji 
The issue with using `getNullableType()` directly is because of the typing definition. We can change the `ensureNullableType()` function to be:

```typescript
export function ensureNullableType(
  type: GraphQLOutputType | GraphQLInputType
): GraphQLNullableType {
  return isNonNullType(type) ? type.ofType : type;
}
```

and that should work fine. If I am not mistaken, that is what `getNullableType()` does anyway.

btw, re the percentage of lines tested, do not worry. The deleted file was fully tested so taking it out of the equation will always reduce the overall % of tested lines.

**Comment by eturino** [comment]
@all-contributors please add @brabeji for bug, tests, code and idea

**Pull request merged**
